name: Build Repo UI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install # เปลี่ยนเป็น npm install เพราะไม่มี package-lock.json

      - name: Build Project
        run: npm run build

      # บีบอัดไฟล์ใน dist ให้กลายเป็น ZIP แล้วปล่อยให้โหลดบน GitHub
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-build-output # ตั้งชื่อไฟล์ ZIP
          path: dist/             # ดึงไฟล์ทั้งหมดจากโฟลเดอร์ dist
          retention-days: 7       # เก็บไฟล์ไว้ดาวน์โหลดได้ 7 วัน
